### PR TITLE
Avoid calling ourselves using `env::current_exe`

### LINKED ISSUE #49: Invoking shimmed command with sudo fails
## Steps to reproduce

You'll need a sacrificial command for this. In my case, I'm going to user `ruby`.

1.  Define command

    ```sh
    alt def ruby test-sys /usr/bin/ruby
    ```

1.  Make sure the shims exist

    ```sh
    alt shim
    ```

1.  Run your command as root

    ```sh
    sudo ruby --version
    ```

`alt` will call itself in a loop complaining that it's not configured properly.

## Why is this happening?

1.  `sudo` invokes `alt` (through a shim)
1.  It passes your user's `PATH` env var (including your user's shim dir `$HOME/.local/alt/shims`)
1.  `alt` tries to find the system version of the command (presuming that `alt` is not configured for the user you're sudoing into)
1.  `alt` finds your original user's shim dir (`$HOME/.local/alt/shims/ruby`) (it didn't filter it out because it thinks the shims dir is the one for the user you sudoed into ex: `/root/.local/alt/shims`)
1.  `alt` invokes its own shim
1.  `goto 1`

## Deeper problem

`alt` can invoke itself in a loop. Seems like it's pretty bad at detecting when it's calling itself.

### PR DESCRIPTION
**Pull request by dotboris**
Fixes #49

### CODE REVIEW

File: src/command.rs [hunk 1]
```diff
@@ -12,14 +12,14 @@ pub fn find_selected_version(command: &str) -> Option<String> {
...
+    fs::canonicalize(&a).unwrap() == fs::canonicalize(&b).unwrap()
+}
 
-    paths.iter()
-        .find(|p| p.join(command).exists())
+pub fn find_system_bin(command: &str, system_path: &str, current_exe: &Path) -> Option<PathBuf> {
+    env::split_paths(&system_path)
         .map(|p| p.join(command))
+        .filter(|p| p.exists())
+        .filter(|p| !realpath_equal(&p, &current_exe))
```
Comment (dotboris) [inline src/command.rs]: In this case, we're going to calling `fs::canonicalize(...)` on `current_exe` a bunch of times. We don't really need this.

File: src/exec_cmd.rs [hunk 2]
```diff
@@ -18,7 +19,11 @@ pub fn run(command: &str, command_args: &[String]) {
                 ))
                 .to_owned()
         })
-        .or_else(|| command::find_system_bin(command));
+        .or_else(|| {
+            let path = env::var("PATH").expect("env var PATH is not defined");
+            let current_exe = env::current_exe().unwrap();
```
Comment (dotboris) [inline src/exec_cmd.rs]: Originally, I made the `current_exe` and `system_path` args so that I could test `find_system_bin()`. The problem is that I haven't really been able to test `find_system_bin()` with this, so what's the point of the new args now.

File: src/command.rs [hunk 3]
```diff
@@ -13,13 +13,15 @@ pub fn find_selected_version(command: &str) -> Option<String> {
 }
 
 pub fn find_system_bin(command: &str) -> Option<PathBuf> {
-    let shim_dir = config::shim_dir();
-    let path = env::var("PATH").expect("env var PATH is not defined");
-    let paths: Vec<_> = env::split_paths(&path)
-        .filter(|p| p != &shim_dir)
-        .collect();
+    let system_path = env::var("PATH").unwrap();
```
Comment (dotboris) [inline src/command.rs]: I don't think that we should panic if the `PATH` is not set. We're trying to find a system bin from a command name. If there's no path then we can't find it that's it. We should return `None`
