### PR TITLE
Tolerate dir in `PATH` not existing during scan

### LINKED ISSUE #21: `alt scan ...` crashes if a path in the PATH does not exist
# Steps to reproduce

```sh
$ env RUST_BACKTRACE=1 PATH="$PATH:/some/bs" alt scan something
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
   9: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &'a mut F>::call_once
  10: <&'a mut I as core::iter::iterator::Iterator>::next
  11: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  12: alt::scan::path_suffix::scan
  13: alt::scan_cmd::run
  14: alt::cli::run
  15: alt::main
  16: std::rt::lang_start::{{closure}}
  17: std::panicking::try::do_call
  18: __rust_maybe_catch_panic
  19: std::rt::lang_start_internal
  20: main
```

This is an edge case, but it should be dealt with.

### PR DESCRIPTION
**Pull request by dotboris**
Closes #21 

We now just ignore any directory read that fails. This is a little aggressive but it catches all kinds of errors including permission issues and fs quirks

### CODE REVIEW

File: src/scan/path_suffix.rs [hunk 1]
```diff
@@ -27,7 +27,7 @@ pub fn scan(command: &str) -> Vec<CommandVersion> {
 
     env::split_paths(&path)
         .filter(|p| p != &shim_dir)
-        .flat_map(|p| fs::read_dir(p).unwrap())
+        .flat_map(|p| fs::read_dir(p).ok()).flatten()
```
Comment (dotboris) [inline src/scan/path_suffix.rs]: Not 100% sure that this is a good idea. We'll be eating every single error.

I'm fine with failing when we can't read the dir for regular reasons: (doesn't exist, no permissions, etc.)

Should we fail when we get a weird FS error. (disk blows up or whatever)

Comment (dotboris) [reply src/scan/path_suffix.rs]: Looks like we can use `is_dir()`. It'll both check for the directory being present and use having the right permissions.

https://devdocs.io/rust/std/path/struct.path#method.is_dir
